import React, { createContext, useContext, useState, useCallback } from 'react';

const LangContext = createContext(null);

const translations = {
  en: {
    // General
    'app.name': 'F&B Financial Control Platform',
    'app.short': 'F&B ERP',
    'common.search': 'Search',
    'common.create': 'Create',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.export': 'Export',
    'common.filter': 'Filter',
    'common.actions': 'Actions',
    'common.status': 'Status',
    'common.date': 'Date',
    'common.amount': 'Amount',
    'common.type': 'Type',
    'common.name': 'Name',
    'common.description': 'Description',
    'common.notes': 'Notes',
    'common.all': 'All',
    'common.loading': 'Loading...',
    'common.no_data': 'No data available',
    'common.sign_in': 'Sign In',
    'common.sign_out': 'Sign Out',
    'common.back': 'Back',
    'common.submit': 'Submit',
    'common.approve': 'Approve',
    'common.reject': 'Reject',
    'common.resolve': 'Resolve',
    'common.previous': 'Previous',
    'common.next': 'Next',
    // Auth
    'auth.welcome': 'Welcome Back',
    'auth.subtitle': 'Sign in to access your portal',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.signing_in': 'Signing in...',
    // Portal
    'portal.select': 'Select Portal',
    'portal.welcome': 'Welcome, {name}. Choose your workspace.',
    'portal.management': 'Management Portal',
    'portal.outlet': 'Outlet Portal',
    'portal.kitchen': 'Kitchen Portal',
    'portal.cashier': 'Cashier Portal',
    'portal.warehouse': 'Warehouse Portal',
    'portal.coming_soon': 'Coming Soon',
    'portal.no_access': 'No Access',
    'portal.your_access': 'Your Access',
    // Sidebar sections
    'nav.executive': 'Executive',
    'nav.finance': 'Finance',
    'nav.inventory': 'Inventory',
    'nav.reports': 'Reports',
    'nav.operations': 'Operations',
    'nav.admin': 'Admin',
    // Pages
    'page.dashboard': 'Dashboard',
    'page.dashboard.subtitle': 'Overview of operations across all outlets',
    'page.alerts': 'Alerts',
    'page.alerts.subtitle': 'Anomaly detection and operational monitoring',
    'page.coa': 'Chart of Accounts',
    'page.coa.subtitle': 'Manage account hierarchy for double-entry bookkeeping',
    'page.journals': 'Journal Entries',
    'page.journals.subtitle': 'Double-entry accounting journal',
    'page.cash_bank': 'Cash & Bank',
    'page.cash_bank.subtitle': 'Manage accounts, cash movements, and settlements',
    'page.reconciliation': 'Reconciliation',
    'page.reconciliation.subtitle': 'Cash & bank reconciliation with variance tracking',
    'page.budgeting': 'Budgeting',
    'page.budgeting.subtitle': 'Budget vs actual by outlet and period',
    'page.recurring': 'Recurring Transactions',
    'page.recurring.subtitle': 'Automated scheduled transactions',
    'page.items_stock': 'Items & Stock',
    'page.items_stock.subtitle': 'Items, stock levels, and movements',
    'page.recipes': 'Recipe & BOM',
    'page.recipes.subtitle': 'Manage recipes, bill of materials, and consumption rules',
    'page.production': 'Production / Prep Orders',
    'page.production.subtitle': 'Manage production batches and prep workflows',
    'page.reports_main': 'Reports',
    'page.reports_main.subtitle': 'Financial and inventory reports with export',
    'page.variance': 'Variance Report',
    'page.variance.subtitle': 'Theoretical vs actual consumption analysis',
    'page.drilldown': 'Drill-Down Reports',
    'page.drilldown.subtitle': 'Click rows to drill deeper into data',
    'page.closing_monitor': 'Outlet Closing Monitor',
    'page.closing_monitor.subtitle': 'Monitor daily closing status across all outlets',
    'page.approvals': 'Approvals',
    'page.approvals.subtitle': 'Review and manage approval requests',
    'page.approval_rules': 'Approval Rules',
    'page.approval_rules.subtitle': 'Configure when transactions require approval',
    'page.admin': 'Admin',
    'page.admin.subtitle': 'Users, roles, permissions, and outlets',
    'page.audit': 'Audit Trail',
    // KPI labels
    'kpi.total_revenue': 'Total Revenue (30d)',
    'kpi.bank_balance': 'Bank Balance',
    'kpi.active_outlets': 'Active Outlets',
    'kpi.pending_approvals': 'Pending Approvals',
    'kpi.active_users': 'Active Users',
    'kpi.inventory_items': 'Inventory Items',
    'kpi.sales_trend': 'Sales Trend (14 Days)',
    'kpi.cash_position': 'Cash Position',
    'kpi.bank_accounts': 'Bank Accounts',
    'kpi.outlet_cash': 'Outlet Cash',
    'kpi.petty_cash': 'Petty Cash',
    // Outlet portal
    'outlet.dashboard': 'Outlet Dashboard',
    'outlet.cash_in': 'Cash In',
    'outlet.cash_out': 'Cash Out',
    'outlet.net_cash': 'Net Cash',
    'outlet.today_sales': 'Today Sales',
    'outlet.daily_closing': 'Daily Closing',
    'outlet.not_started': 'Not Started',
    'outlet.start_closing': 'Start Closing',
    'outlet.submit_approval': 'Submit for Approval',
    'outlet.complete_tasks': 'Complete all required tasks before submitting',
    'outlet.sales_summary': 'Sales Summary',
    'outlet.cash_management': 'Cash Management',
    'outlet.petty_cash': 'Petty Cash',
  },
  id: {
    // General
    'app.name': 'F&B Platform Kontrol Keuangan',
    'app.short': 'F&B ERP',
    'common.search': 'Cari',
    'common.create': 'Buat',
    'common.save': 'Simpan',
    'common.cancel': 'Batal',
    'common.delete': 'Hapus',
    'common.edit': 'Ubah',
    'common.export': 'Ekspor',
    'common.filter': 'Filter',
    'common.actions': 'Aksi',
    'common.status': 'Status',
    'common.date': 'Tanggal',
    'common.amount': 'Jumlah',
    'common.type': 'Tipe',
    'common.name': 'Nama',
    'common.description': 'Deskripsi',
    'common.notes': 'Catatan',
    'common.all': 'Semua',
    'common.loading': 'Memuat...',
    'common.no_data': 'Tidak ada data',
    'common.sign_in': 'Masuk',
    'common.sign_out': 'Keluar',
    'common.back': 'Kembali',
    'common.submit': 'Kirim',
    'common.approve': 'Setujui',
    'common.reject': 'Tolak',
    'common.resolve': 'Selesaikan',
    'common.previous': 'Sebelumnya',
    'common.next': 'Berikutnya',
    // Auth
    'auth.welcome': 'Selamat Datang',
    'auth.subtitle': 'Masuk untuk mengakses portal Anda',
    'auth.email': 'Email',
    'auth.password': 'Kata Sandi',
    'auth.signing_in': 'Sedang masuk...',
    // Portal
    'portal.select': 'Pilih Portal',
    'portal.welcome': 'Selamat datang, {name}. Pilih ruang kerja Anda.',
    'portal.management': 'Portal Manajemen',
    'portal.outlet': 'Portal Outlet',
    'portal.kitchen': 'Portal Dapur',
    'portal.cashier': 'Portal Kasir',
    'portal.warehouse': 'Portal Gudang',
    'portal.coming_soon': 'Segera Hadir',
    'portal.no_access': 'Tidak Ada Akses',
    'portal.your_access': 'Akses Anda',
    // Sidebar sections
    'nav.executive': 'Eksekutif',
    'nav.finance': 'Keuangan',
    'nav.inventory': 'Inventaris',
    'nav.reports': 'Laporan',
    'nav.operations': 'Operasional',
    'nav.admin': 'Admin',
    // Pages
    'page.dashboard': 'Dasbor',
    'page.dashboard.subtitle': 'Ringkasan operasi seluruh outlet',
    'page.alerts': 'Peringatan',
    'page.alerts.subtitle': 'Deteksi anomali dan pemantauan operasional',
    'page.coa': 'Bagan Akun',
    'page.coa.subtitle': 'Kelola hierarki akun untuk pembukuan berpasangan',
    'page.journals': 'Jurnal Entri',
    'page.journals.subtitle': 'Jurnal akuntansi berpasangan',
    'page.cash_bank': 'Kas & Bank',
    'page.cash_bank.subtitle': 'Kelola akun, pergerakan kas, dan setelmen',
    'page.reconciliation': 'Rekonsiliasi',
    'page.reconciliation.subtitle': 'Rekonsiliasi kas & bank dengan pelacakan selisih',
    'page.budgeting': 'Anggaran',
    'page.budgeting.subtitle': 'Anggaran vs realisasi per outlet dan periode',
    'page.recurring': 'Transaksi Berulang',
    'page.recurring.subtitle': 'Transaksi terjadwal otomatis',
    'page.items_stock': 'Barang & Stok',
    'page.items_stock.subtitle': 'Barang, level stok, dan pergerakan',
    'page.recipes': 'Resep & BOM',
    'page.recipes.subtitle': 'Kelola resep, bill of materials, dan aturan konsumsi',
    'page.production': 'Order Produksi',
    'page.production.subtitle': 'Kelola batch produksi dan alur kerja prep',
    'page.reports_main': 'Laporan',
    'page.reports_main.subtitle': 'Laporan keuangan dan inventaris dengan ekspor',
    'page.variance': 'Laporan Varians',
    'page.variance.subtitle': 'Analisis konsumsi teoritis vs aktual',
    'page.drilldown': 'Laporan Drill-Down',
    'page.drilldown.subtitle': 'Klik baris untuk melihat data lebih detail',
    'page.closing_monitor': 'Monitor Penutupan Outlet',
    'page.closing_monitor.subtitle': 'Pantau status penutupan harian seluruh outlet',
    'page.approvals': 'Persetujuan',
    'page.approvals.subtitle': 'Tinjau dan kelola permintaan persetujuan',
    'page.approval_rules': 'Aturan Persetujuan',
    'page.approval_rules.subtitle': 'Konfigurasi kapan transaksi perlu persetujuan',
    'page.admin': 'Admin',
    'page.admin.subtitle': 'Pengguna, peran, izin, dan outlet',
    'page.audit': 'Jejak Audit',
    // KPI labels
    'kpi.total_revenue': 'Total Pendapatan (30h)',
    'kpi.bank_balance': 'Saldo Bank',
    'kpi.active_outlets': 'Outlet Aktif',
    'kpi.pending_approvals': 'Persetujuan Tertunda',
    'kpi.active_users': 'Pengguna Aktif',
    'kpi.inventory_items': 'Item Inventaris',
    'kpi.sales_trend': 'Tren Penjualan (14 Hari)',
    'kpi.cash_position': 'Posisi Kas',
    'kpi.bank_accounts': 'Rekening Bank',
    'kpi.outlet_cash': 'Kas Outlet',
    'kpi.petty_cash': 'Kas Kecil',
    // Outlet portal
    'outlet.dashboard': 'Dasbor Outlet',
    'outlet.cash_in': 'Kas Masuk',
    'outlet.cash_out': 'Kas Keluar',
    'outlet.net_cash': 'Kas Bersih',
    'outlet.today_sales': 'Penjualan Hari Ini',
    'outlet.daily_closing': 'Penutupan Harian',
    'outlet.not_started': 'Belum Dimulai',
    'outlet.start_closing': 'Mulai Penutupan',
    'outlet.submit_approval': 'Kirim untuk Persetujuan',
    'outlet.complete_tasks': 'Selesaikan semua tugas sebelum mengirim',
    'outlet.sales_summary': 'Ringkasan Penjualan',
    'outlet.cash_management': 'Manajemen Kas',
    'outlet.petty_cash': 'Kas Kecil',
  }
};

export const LangProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('fnb_lang') || 'en';
  });

  const changeLang = (newLang) => {
    setLang(newLang);
    localStorage.setItem('fnb_lang', newLang);
  };

  const t = useCallback((key, params = {}) => {
    let text = translations[lang]?.[key] || translations.en?.[key] || key;
    Object.entries(params).forEach(([k, v]) => {
      text = text.replace(`{${k}}`, v);
    });
    return text;
  }, [lang]);

  return (
    <LangContext.Provider value={{ lang, changeLang, t }}>
      {children}
    </LangContext.Provider>
  );
};

export const useLang = () => {
  const context = useContext(LangContext);
  if (!context) throw new Error('useLang must be used within LangProvider');
  return context;
};
